"""Add default value to postponed and cancelled

Revision ID: 3392246617f4
Revises: da95e43ba728
Create Date: 2026-03-18 23:09:23.641460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3392246617f4'
down_revision: Union[str, Sequence[str], None] = 'da95e43ba728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'postponed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.false())
    op.alter_column('events', 'cancelled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'cancelled',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('events', 'postponed',
               existing_type=sa.BOOLEAN(),
               default=False)
    # ### end Alembic commands ###
