"""Add slug to Category model

Revision ID: 6c5c0df3618f
Revises: 9ee5e23ad6f1
Create Date: 2026-01-25 13:22:23.016485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5c0df3618f'
down_revision: Union[str, Sequence[str], None] = '9ee5e23ad6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(), nullable=True)) # Added as nullable first
    # Populate existing rows with a slug derived from the name
    op.execute("UPDATE categories SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL")
    # Alter column to be non-nullable
    op.alter_column('categories', 'slug', existing_type=sa.String(), nullable=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
