"""Make timezone non-nullable in Session model

Revision ID: 9ee5e23ad6f1
Revises: a7fa39f42bdd
Create Date: 2026-01-24 23:11:07.334736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee5e23ad6f1'
down_revision: Union[str, Sequence[str], None] = 'a7fa39f42bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing NULL values to 'UTC'
    op.execute("UPDATE sessions SET timezone = 'UTC' WHERE timezone IS NULL")
    
    op.alter_column('sessions', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_nullable=False) # Add existing_nullable=False
    # ### end Alembic commands ###
