"""Add timezone to Session model

Revision ID: a7fa39f42bdd
Revises: 59f5f0f3125a
Create Date: 2026-01-24 23:03:12.214269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fa39f42bdd'
down_revision: Union[str, Sequence[str], None] = '59f5f0f3125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'timezone')
    # ### end Alembic commands ###
