"""Add Postponed and Cancelled field to Events

Revision ID: da95e43ba728
Revises: 28c236c20d77
Create Date: 2026-03-18 22:56:33.004356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da95e43ba728'
down_revision: Union[str, Sequence[str], None] = '28c236c20d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('postponed', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cancelled')
    op.drop_column('events', 'postponed')
    # ### end Alembic commands ###
